routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

// Admin & Publisher
Route::group(['middleware' => ['auth', 'role:admin,publisher']], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/news', 'NewsController')->except(['show']);

    // Uploads
    Route::get('/upload/image', 'UploadController@image_get')->name('upload.image');
    Route::post('/upload/image', 'UploadController@image_create')->name('upload.image');
    Route::delete('/upload/image', 'UploadController@image_delete')->name('upload.image');

    // Settings
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings', 'SettingsController@update')->name('settings');
});

// Only Admin
Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('/users', 'UsersController')->except(['show', 'create', 'store', 'destroy']);
    Route::post('/users/update_role', 'UsersController@updateRole');
    Route::post('/news/approve_news', 'NewsController@approveNews');

    Route::resource('/news_comments', 'NewsCommentsController')->except(['show', 'create', 'store', 'edit', 'update']);
    Route::post('/news_comments/approve_comment', 'NewsCommentsController@approveComment');
    Route::resource('/news_categories', 'NewsCategoriesController')->except(['show']);
    Route::resource('/stories', 'StoriesController')->except(['show']);
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laravel\Passport\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username',
        'first_name',
        'last_name',
        'image_name',
        'phone_number',
        'email',
        'address',
        'password',
        'is_admin',
        'is_publisher',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class UsersController extends Controller
{
    function index()
    {
        $users = User::all();
        return view('users.index')->with('users', $users);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $user = User::findOrFail($id);
        return view('users.edit')->with('user', $user);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), [
            'first_name' => 'required',
            'last_name' => 'required',
            'username' => 'required',
            'email' => 'required|email'
        ]);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }

        $user = User::findOrFail($id);
        $user->first_name = $request->input('first_name');
        $user->last_name = $request->input('last_name');
        $user->phone_number = $request->input('phone_number');
        $user->email = $request->input('email');
        $user->address = $request->input('address');

        $usernameFromForm = strtolower($request->input('username'));
        $usernameFromDB = strtolower($user->username);

        if ($usernameFromForm != $usernameFromDB) {
            if (User::where('username', $usernameFromForm)->exists()) {
                $validator->errors()->add('username', 'This username is already taken');
                return back()->withErrors($validator)->withInput();
            }
            $user->username = $usernameFromForm;
        }

        $emailFromForm = strtolower($request->input('email'));
        $emailFromDB = strtolower($user->email);

        if ($emailFromForm != $emailFromDB) {
            if (User::where('email', $emailFromForm)->exists()) {
                $validator->errors()->add('email', 'This email is already taken');
                return back()->withErrors($validator)->withInput();
            }
            $user->email = $emailFromForm;
        }

        $user->update();

        return redirect(route('users.index'))->with('status', 'User updated!');
    }

    function updateRole(Request $request)
    {
        $userId = (int) $request->get('userId');
        $role = $request->get('role');
        $isChecked = filter_var($request->get('isChecked'), FILTER_VALIDATE_BOOLEAN);

        $user = User::findOrFail($userId);
        if ($role == 'admin') {
            $user->is_admin = $isChecked;
        } else if ($role == 'publisher') {
            $user->is_publisher = $isChecked;
        }
        $user->update();
        return response([(int) $userId, $role,  $isChecked]);
    }
}

resources/views/users/edit.blade.php
@extends('layouts.master')

@section('content')

<h1>Edit</h1>

<h4>User</h4>
<hr />
<div class="row">
    <div class="col-lg-6">
        <form action="{{ route("users.update", [ 'id' => $user->id ]) }}" method="POST">
            {{ csrf_field() }}
            @method('PUT')

            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label class="control-label">First Name</label>
                        <input class="form-control" name="first_name" value="{{ old('first_name', $user->first_name) }}" />
                        @if ($errors->has('first_name'))
                        <small class="text-validation-error text-danger">{{$errors->first('first_name')}}</small>
                        @endif
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label class="control-label">Last Name</label>
                        <input class="form-control" name="last_name" value="{{ old('last_name', $user->last_name) }}" />
                        <small class="text-validation-error text-danger">{{$errors->first('last_name')}}</small>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-6">
                    <div class="form-group">
                        <label class="control-label">Phone Number</label>
                        <input class="form-control" type="tel" name="phone_number" value="{{ old('phone_number', $user->phone_number) }}" />
                        <small class="text-validation-error text-danger">{{$errors->first('phone_number')}}</small>
                    </div>
                </div>
                <div class="col-6">
                    <div class="form-group">
                        <label class="control-label">Email</label>
                        <input class="form-control" type="email" name="email" value="{{ old('email', $user->email) }}" />
                        <small class="text-validation-error text-danger">{{$errors->first('email')}}</small>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Username</label>
                <input class="form-control" name="username" value="{{ old('username', $user->username) }}" />
                <small class="text-validation-error text-danger">{{$errors->first('username')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Address</label>
                <input class="form-control" name="address" value="{{ old('address', $user->address) }}" />
            </div>
            <input type="submit" value="Save" class="btn btn-primary" />
        </form>
    </div>
</div>

@endsection

resources/views/users/index.blade.php
@extends('layouts.master')

@section('content')

<div class="d-flex flex-row align-items-center">
    <h3>
        Users
    </h3>
</div>

<hr />

<table id="usersTable" class="table table-striped">
    <thead>
        <tr>
            <th>
                FirstName
            </th>
            <th>
                LastName
            </th>
            <th>
                PhoneNumber
            </th>
            <th>
                Email
            </th>
            <th>
                Username
            </th>
            <th>
                IsAdmin
            </th>
            <th>
                IsPublisher
            </th>
            <th>
                Address
            </th>
            <th>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach ($users as $item)
        <tr>
            <td>
                {{ $item->first_name }}
            </td>
            <td>
                {{ $item->last_name }}
            </td>
            <td>
                {{ $item->phone_number }}
            </td>
            <td>
                {{ $item->email }}
            </td>
            <td>
                {{ $item->username }}
            </td>
            <td>
                <input type="checkbox" {{ Auth::user()->id == $item->id ? 'disabled' : '' }} {{ $item->is_admin ? 'checked' : '' }} onclick="handleChecked('admin', this, {{ $item->id }});" />
            </td>
            <td>
                <input type="checkbox" {{ $item->is_publisher ? 'checked' : '' }} onclick="handleChecked('publisher', this, {{ $item->id }});" />
            </td>
            <td>
                {{ $item->address }}
            </td>
            <td>
                <a href="{{ route('users.edit', ['id' => $item->id]) }}" class="btn btn-info btn-sm"><span data-feather="edit-2"></span></a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@endsection

@push('scripts')
<script>
    $(document).ready(function () {

createTable("#usersTable");
    });

    function handleChecked(role, cb, id) {

        $.ajax({
            type: "POST",
            url: "/users/update_role",
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
            dataType: 'json',
            data: {
                role: role,
                userId: id,
                isChecked: cb.checked
            },
            success: () => {}
        })
    }
</script>
@endpush