routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

// Admin & Publisher
Route::group(['middleware' => ['auth', 'role:admin,publisher']], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/news', 'NewsController')->except(['show']);

    // Uploads
    Route::get('/upload/image', 'UploadController@image_get')->name('upload.image');
    Route::post('/upload/image', 'UploadController@image_create')->name('upload.image');
    Route::delete('/upload/image', 'UploadController@image_delete')->name('upload.image');

    // Settings
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings', 'SettingsController@update')->name('settings');
});

// Only Admin
Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('/users', 'UsersController')->except(['show', 'create', 'store', 'destroy']);
    Route::post('/users/update_role', 'UsersController@updateRole');
    Route::post('/news/approve_news', 'NewsController@approveNews');

    Route::resource('/news_comments', 'NewsCommentsController')->except(['show', 'create', 'store', 'edit', 'update']);
    Route::post('/news_comments/approve_comment', 'NewsCommentsController@approveComment');
    Route::resource('/news_categories', 'NewsCategoriesController')->except(['show']);
    Route::resource('/stories', 'StoriesController')->except(['show']);
});

app/Models/NewsCategory.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class NewsCategory extends Model
{
    protected $table = "news_categories";
    protected $fillable = ['name', 'color', 'image_name'];

    public function news()
    {
        return $this->hasMany('App\Models\News', 'category_id');
    }
}

app/Http/Controllers/NewsCategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Library\FileHelper;
use App\Models\NewsCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;

class NewsCategoriesController extends BaseController
{
    public $validationRules = [
        'name' => 'required',
        'color' => 'required',
        'image_name' => 'required',
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $newsCategories = NewsCategory::all();
        return view('news_categories.index')->with('newsCategories', $newsCategories);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news_categories.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), $this->validationRules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }
        $imageName = $request->input('image_name');

        $newsCategory = new NewsCategory;
        $newsCategory->name = $request->input('name');
        $newsCategory->color = $request->input('color');
        $newsCategory->image_name = $imageName;
        $newsCategory->save();
        FileHelper::moveCacheToImages($imageName);
        return redirect('news_categories');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $newsCategory = NewsCategory::findOrFail($id);
        return view('news_categories.edit')->with('newsCategory', $newsCategory);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->validationRules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }
        $imageName =  $request->input('image_name');
        $newsCategory = NewsCategory::findOrFail($id);
        if ($newsCategory->image_name != $imageName) {
            FileHelper::removeImageFile($newsCategory->image_name);
        }
        $newsCategory->name = $request->input('name');
        $newsCategory->color = $request->input('color');
        $newsCategory->image_name = $imageName;
        $newsCategory->update();
        FileHelper::moveCacheToImages($imageName);
        return redirect('news_categories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $newsCategory = NewsCategory::findOrFail($id);
        $newsCategory->delete();
        FileHelper::removeImageFile($newsCategory->image_name);
        return redirect('news_categories');
    }
}

app/Http/Controllers/api/v1/NewsCategoryController.php
<?php

namespace App\Http\Controllers\api\v1;

use App\Models\News;
use App\Models\NewsCategory;

class NewsCategoryController extends BaseAPIController
{
    public function index()
    {
        $newsCategories = NewsCategory::withCount('news')->get();
        return $this->responseJSON($newsCategories);
    }

    public function news($categoryId)
    {
        $news = News::with('category', 'user', 'topComments')
            ->withCount('comments')
            ->where('category_id', $categoryId)
            ->where('visible', 1)
            ->where('approved', 1)
            ->orderByRaw('news.created_at DESC')
            ->get();

        return $this->responseJSON($news);
    }
}

resources/views/news_categories/create.blade.php
@extends('layouts.master')

@section('content')

<h1>Create</h1>

<h4>News Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="{{ route('news_categories.store') }}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" id="image_name" name="image_name" />
            <div class="form-group">
                <label class="control-label">Name</label>
                <input type="text" name="name" class="form-control" value="{{ old('name') }}" required />
                <small class="text-validation-error text-danger">{{$errors->first('name')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Color</label>
                <input type="text" id="color" name="color" style="color: white" autocomplete="off" class="form-control" value="{{ old('color') }}" required />
                <small class="text-validation-error text-danger">{{$errors->first('color')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Background Image</label>
                <input id="imageFile" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('image_name')}}</small>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="{{route('news_categories.index')}}">Back to List</a>
</div>

@endsection

@push('scripts')
@include('partials.file_pond_scripts')

<script>
    $(document).ready(() => {
        $('#color').colorpicker();
        $('#color').on('colorpickerChange', function(event) {
            $('#color').css('background-color', event.color.toString());
        });
        $('#color').css('background-color', $('#color').val());
        createFilePond("imageFile", "image_name");
    });
</script>
@endpush

resources/views/news_categories/edit.blade.php
@extends('layouts.master')

@section('content')

<h1>Edit</h1>

<h4>News Category</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form action="{{ route('news_categories.update', ['id' => $newsCategory->id]) }}" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            <input type="hidden" id="image_name" name="image_name" value="{{ old('image_name', $newsCategory->image_name) }}" />
            <div class="form-group">
                <label class="control-label">Name</label>
                <input type="text" name="name" class="form-control" value="{{ old('name', $newsCategory->name) }}" required />
                <small class="text-validation-error text-danger">{{$errors->first('name')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Color</label>
                <input type="text" id="color" name="color" class="form-control" style="color: white" value="{{ old('color', $newsCategory->color) }}" required />
                <small class="text-validation-error text-danger">{{$errors->first('color')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Background Image</label>
                <input id="imageFile" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('image_name')}}</small>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="{{route('news_categories.index')}}">Back to List</a>
</div>

@endsection

@push('scripts')
@include('partials.file_pond_scripts')
<script>
    $(document).ready(() => {
        $('#color').colorpicker();
        $('#color').on('colorpickerChange', function(event) {
            $('#color').css('background-color', event.color.toString());
        });
        $('#color').css('background-color', $('#color').val());
        createFilePond("imageFile", "image_name");
    });
</script>
@endpush

resources/views/news_categories/index.blade.php
@extends('layouts.master')

@section('content')

<div class="d-flex flex-row align-items-center">
    <h3>
        News Categories
    </h3>
    <a class="btn btn-info btn-sm ml-auto" href="{{ route('news_categories.create') }}">Create News Category</a>
</div>

<hr />

<table id="newsCategoriesTable" class="table table-striped">
    <thead>
        <tr>
            <th>
                Name
            </th>
            <th>
                Color
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach ($newsCategories as $item)
        <tr>
            <td>
                {{$item->name}}
            </td>
            <td>
                <div style="width: 22px; height: 22px; background-color: {{$item->color}}" />
            </td>
            <td>
                <a href="{{ route('news_categories.edit', ['id' => $item->id]) }}" class="btn btn-info btn-sm"><span data-feather="edit-2"></span></a>
                <a href="javascript:void(0);" data-entity-id="{{$item->id}}" class="btn btn-danger btn-sm delete-btn"><span data-feather="trash-2"></span></a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@include('partials.delete_confirm_modal', ['actionName' => 'news_categories'])

@endsection

@push('scripts')
<script>
    $(document).ready(function () {
        createTable("#newsCategoriesTable");
    });
</script>
@endpush