routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

// Admin & Publisher
Route::group(['middleware' => ['auth', 'role:admin,publisher']], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/news', 'NewsController')->except(['show']);

    // Uploads
    Route::get('/upload/image', 'UploadController@image_get')->name('upload.image');
    Route::post('/upload/image', 'UploadController@image_create')->name('upload.image');
    Route::delete('/upload/image', 'UploadController@image_delete')->name('upload.image');

    // Settings
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings', 'SettingsController@update')->name('settings');
});

// Only Admin
Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('/users', 'UsersController')->except(['show', 'create', 'store', 'destroy']);
    Route::post('/users/update_role', 'UsersController@updateRole');
    Route::post('/news/approve_news', 'NewsController@approveNews');

    Route::resource('/news_comments', 'NewsCommentsController')->except(['show', 'create', 'store', 'edit', 'update']);
    Route::post('/news_comments/approve_comment', 'NewsCommentsController@approveComment');
    Route::resource('/news_categories', 'NewsCategoriesController')->except(['show']);
    Route::resource('/stories', 'StoriesController')->except(['show']);
});

app/Models/Story.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class Story extends Model
{
    protected $table = "stories";
    protected $fillable = [
        'related_news_id',
        'user_id',
        'title',
        'content',
        'thumbnail_image_name',
        'story_image_name',
        'visible',
    ];

    public function related_news()
    {
        return $this->belongsTo(News::class, 'related_news_id')->with('category', 'topComments');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }
}

app/Http/Controllers/StoriesController.php
<?php

namespace App\Http\Controllers;

use App\Library\FileHelper;
use App\Models\News;
use App\Models\NewsCategory;
use App\Models\Story;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class StoriesController extends Controller
{
    public $validationRules = [
        'related_news_id' => 'required',
        'title' => 'required',
        'content' => 'required',
        'thumbnail_image_name' => 'required',
        'story_image_name' => 'required',
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $stories = Story::orderBy('created_at', 'desc')->get();
        return view('stories.index', ['stories' => $stories]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $news = News::where('visible', 1)
            ->where('approved', 1)
            ->get();
        return view('stories.create', ['news' => $news]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), $this->validationRules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }
        $thumbnailImageName = $request->input('thumbnail_image_name');
        $storyImageName = $request->input('story_image_name');
        $story = new Story;
        $story->user_id = Auth::user()->id;
        $story->related_news_id = $request->input('related_news_id');
        $story->title = $request->input('title');
        $story->content = $request->input('content');
        $story->visible = filter_var($request->input('visible'), FILTER_VALIDATE_BOOLEAN);
        $story->thumbnail_image_name = $thumbnailImageName;
        $story->story_image_name = $storyImageName;

        $story->save();
        FileHelper::moveCacheToImages($thumbnailImageName);
        FileHelper::moveCacheToImages($storyImageName);
        return redirect('stories');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $story = Story::findOrFail($id);
        $news = News::all();
        return view('stories.edit', ['story' => $story, 'news' => $news]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->validationRules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }
        $thumbnailImageName = $request->input('thumbnail_image_name');
        $storyImageName = $request->input('story_image_name');
        $story = Story::findOrFail($id);
        if ($story->thumbnail_image_name != $thumbnailImageName) {
            FileHelper::removeImageFile($story->thumbnail_image_name);
        }
        if ($story->story_image_name != $storyImageName) {
            FileHelper::removeImageFile($story->story_image_name);
        }
        $story->related_news_id = $request->input('related_news_id');
        $story->title = $request->input('title');
        $story->content = $request->input('content');
        $story->visible = filter_var($request->input('visible'), FILTER_VALIDATE_BOOLEAN);
        $story->thumbnail_image_name = $thumbnailImageName;
        $story->story_image_name = $storyImageName;
        $story->update();

        FileHelper::moveCacheToImages($thumbnailImageName);
        FileHelper::moveCacheToImages($storyImageName);

        return redirect('stories');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $story = Story::findOrFail($id);
        FileHelper::removeImageFile($story->thumbnail_image_name);
        FileHelper::removeImageFile($story->story_image_name);
        $story->delete();
        return redirect('stories');
    }
}

resources/views/stories/create.blade.php
@extends('layouts.master')

@section('content')

<h1>Create</h1>

<h4>Story</h4>
<hr />
<div class="row">
    <div class="col-xl-12">
        <form action="{{route("stories.store")}}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" id="thumbnail_image_name" name="thumbnail_image_name" value="{{ old('thumbnail_image_name') }}" />
            <input type="hidden" id="story_image_name" name="story_image_name" value="{{ old('story_image_name') }}" />
            <div class="row">
                <div class="col-sm-9">
                    <div class="form-group">
                        <label for="related_news_id" class="control-label">Related News</label>
                        <select name="related_news_id" class="form-control">
                            @foreach ($news as $item)
                            <option value="{{ $item->id }}" {{ $item->id == old('related_news_id') ? "selected" : "" }}>
                                {{ $item->title }}
                            </option>
                            @endforeach
                        </select>
                        <small class="text-validation-error text-danger">{{$errors->first('related_news_id')}}</small>
                    </div>
                </div>
                <div class="col-sm-3 mt-2">
                    <div class="form-group form-check mt-4">
                        <label class="form-check-label">
                            <input name="visible" type="checkbox" class="form-check-input" {{ filter_var(old('visible', true), FILTER_VALIDATE_BOOLEAN) ? "checked" : "" }} /> Visible
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="title" class="control-label">Title</label>
                <input name="title" class="form-control" value="{{ old('title') }}" required />
                <small class="text-validation-error text-danger">{{$errors->first('title')}}</small>
            </div>
            <div class="form-group">
                <label for="content" class="control-label">Content</label>
                <textarea id="content" name="content" class="form-control textarea-editor">{{ old('content') }}</textarea>
                <small class="text-validation-error text-danger">{{$errors->first('content')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Thumbnail Photo (square)</label>
                <input id="imageFileForThumbnail" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('thumbnail_image_name')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Story Photo (portrait)</label>
                <input id="imageFileForStory" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('story_image_name')}}</small>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="{{route('stories.index')}}">Back to List</a>
</div>

@endsection

@push('scripts')
@include('partials.file_pond_scripts')
<script>
    $(document).ready(() => {
        $('.textarea-editor').summernote({
            height: 300
        });
        createFilePond("imageFileForThumbnail", "thumbnail_image_name");
        createFilePond("imageFileForStory", "story_image_name");
    });
</script>
@endpush

resources/views/stories/edit.blade.php
@extends('layouts.master')

@section('content')

<h1>Edit</h1>

<h4>Story</h4>
<hr />
<div class="row">
    <div class="col-xl-12">
        <form action="{{route("stories.update", ['id' => $story->id ])}}" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            <input type="hidden" id="thumbnail_image_name" name="thumbnail_image_name" value="{{ old('thumbnail_image_name', $story->thumbnail_image_name) }}" />
            <input type="hidden" id="story_image_name" name="story_image_name" value="{{ old('story_image_name', $story->story_image_name) }}" />

            <div class="row">
                <div class="col-sm-9">
                    <div class="form-group">
                        <label for="related_news_id" class="control-label">Related News</label>
                        <select name="related_news_id" class="form-control">
                            @foreach ($news as $item)
                            <option value="{{ $item->id }}" {{ $item->id == old('related_news_id', $story->related_news_id) ? "selected" : "" }}>
                                {{ $item->title }}
                            </option>
                            @endforeach
                        </select>
                        <small class="text-validation-error text-danger">{{$errors->first('related_news_id')}}</small>
                    </div>
                </div>
                <div class="col-sm-3 mt-2">
                    <div class="form-group form-check mt-4">
                        <label class="form-check-label">
                            <input name="visible" type="checkbox" {{ filter_var(old('visible', $story->visible), FILTER_VALIDATE_BOOLEAN) ? "checked" : "" }} class="form-check-input" /> Visible
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Title</label>
                <input name="title" class="form-control" value="{{ old('title', $story->title) }}" required />
                <small class="text-validation-error text-danger">{{ $errors->first('title') }}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Content</label>
                <textarea name="content" class="form-control textarea-editor">{{ old('content', $story->content) }}</textarea>
                <small class="text-validation-error text-danger">{{ $errors->first('content') }}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Thumbnail Photo (square)</label>
                <input id="imageFileForThumbnail" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('thumbnail_image_name')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Story Photo (portrait)</label>
                <input id="imageFileForStory" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('story_image_name')}}</small>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="{{route('news.index')}}">Back to List</a>
</div>

@endsection

@push('scripts')
@include('partials.file_pond_scripts')
<script>
    $(document).ready(() => {
        $('.textarea-editor').summernote({
            height: 300
        });
        createFilePond("imageFileForThumbnail", "thumbnail_image_name");
        createFilePond("imageFileForStory", "story_image_name");
    });
</script>
@endpush

resources/views/stories/index.blade.php
@extends('layouts.master')

@section('content')

<div class="d-flex flex-row align-items-center">
    <h3>
        Stories
    </h3>
    <a class="btn btn-info btn-sm ml-auto" href="/stories/create">Create Story</a>
</div>

<hr />

<table id="storiesTable" class="table table-striped">
    <thead>
        <tr>
            <th>
                Title
            </th>
            <th>
                User
            </th>
            <th>
                Releated News
            </th>
            <th>
                Visibility
            </th>
            <th>
                Created Date
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach ($stories as $item)
        <tr>
            <td>
                {{$item->title}}
            </td>
            <td>
                {{$item->user->username}}
            </td>
            <td>
                {{$item->related_news->title}}
            </td>
            <td>
                {{ filter_var($item->visible, FILTER_VALIDATE_BOOLEAN) ? 'visible' : 'unvisible' }}
            </td>
            <td>
                {{$item->created_at}}
            </td>
            <td>
                <a href="{{ route('stories.edit', ['id' => $item->id]) }}" class="btn btn-info btn-sm"><span data-feather="edit-2"></span></a>
                <a href="javascript:void(0);" data-entity-id="{{$item->id}}" class="btn btn-danger btn-sm delete-btn"><span data-feather="trash-2"></span></a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@include('partials.delete_confirm_modal', ['actionName' => 'stories'])

@endsection

@push('scripts')
<script>
    $(document).ready(function () {
        createTable("#storiesTable");
    });
</script>
@endpush