routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Auth::routes();

// Admin & Publisher
Route::group(['middleware' => ['auth', 'role:admin,publisher']], function () {
    Route::get('/', 'DashboardController@index');
    Route::resource('/news', 'NewsController')->except(['show']);

    // Uploads
    Route::get('/upload/image', 'UploadController@image_get')->name('upload.image');
    Route::post('/upload/image', 'UploadController@image_create')->name('upload.image');
    Route::delete('/upload/image', 'UploadController@image_delete')->name('upload.image');

    // Settings
    Route::get('/settings', 'SettingsController@index')->name('settings');
    Route::post('/settings', 'SettingsController@update')->name('settings');
});

// Only Admin
Route::group(['middleware' => ['auth', 'role:admin']], function () {
    Route::resource('/users', 'UsersController')->except(['show', 'create', 'store', 'destroy']);
    Route::post('/users/update_role', 'UsersController@updateRole');
    Route::post('/news/approve_news', 'NewsController@approveNews');

    Route::resource('/news_comments', 'NewsCommentsController')->except(['show', 'create', 'store', 'edit', 'update']);
    Route::post('/news_comments/approve_comment', 'NewsCommentsController@approveComment');
    Route::resource('/news_categories', 'NewsCategoriesController')->except(['show']);
    Route::resource('/stories', 'StoriesController')->except(['show']);
});

app/Models/News.php
<?php

namespace App\Models;

use App\User;
use Illuminate\Database\Eloquent\Model;

class News extends Model
{
    protected $table = "news";
    protected $fillable = [
        'category_id',
        'user_id',
        'title',
        'content',
        'image_name',
        'approved',
        'featured',
        'visible',
    ];

    public function category()
    {
        return $this->belongsTo(NewsCategory::class, 'category_id');
    }

    public function user()
    {
        return $this->belongsTo(User::class, 'user_id');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\NewsComment', 'news_id')->where('approved', 1);
    }

    public function topComments()
    {
        return $this->hasMany('App\Models\NewsComment', 'news_id')->with('user')->where('approved', 1)->orderBy('created_at', 'desc')->take(3);
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Library\FileHelper;
use App\Models\News;
use App\Models\NewsCategory;
use Illuminate\Auth\Access\AuthorizationException;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class NewsController extends Controller
{
    public $validationRules = [
        'category_id' => 'required',
        'title' => 'required',
        'content' => 'required',
        'image_name' => 'required',
    ];

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $news = Auth::user()->is_admin ?
            News::orderBy('approved', 'asc')->orderBy('created_at', 'desc')->get() :
            News::where('user_id', Auth::user()->id)->orderBy('approved', 'asc')->orderBy('created_at', 'desc')->get();
        return view('news.index', ['news' => $news]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('news.create', ['news_categories' => NewsCategory::all()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), $this->validationRules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }
        $imageName = $request->input('image_name');
        $news = new News;
        $news->user_id = Auth::user()->id;
        $news->category_id = $request->input('category_id');
        $news->title = $request->input('title');
        $news->content = $request->input('content');
        $news->featured = filter_var($request->input('featured'), FILTER_VALIDATE_BOOLEAN);
        $news->visible = filter_var($request->input('visible'), FILTER_VALIDATE_BOOLEAN);
        $news->image_name = $imageName;

        $autoApproveMode = env('AUTO_APPROVE_FOR_NEWS', false);
        $news->approved = filter_var($autoApproveMode, FILTER_VALIDATE_BOOLEAN);

        $news->save();
        FileHelper::moveCacheToImages($imageName);
        return redirect('news');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $news = News::findOrFail($id);
        $newsCategories = NewsCategory::all();
        return view('news.edit', ['news' => $news, 'news_categories' => $newsCategories]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->validationRules);
        if ($validator->fails()) {
            return back()->withErrors($validator)->withInput();
        }
        $imageName = $request->input('image_name');
        $news = News::findOrFail($id);
        if ($news->image_name != $imageName) {
            FileHelper::removeImageFile($news->image_name);
        }
        $news->category_id = $request->input('category_id');
        $news->title = $request->input('title');
        $news->content = $request->input('content');
        $news->featured = filter_var($request->input('featured'), FILTER_VALIDATE_BOOLEAN);
        $news->visible = filter_var($request->input('visible'), FILTER_VALIDATE_BOOLEAN);
        $news->image_name = $imageName;
        $news->update();
        FileHelper::moveCacheToImages($imageName);
        return redirect('news');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $news = News::findOrFail($id);
        FileHelper::removeImageFile($news->image_name);
        $news->delete();
        return redirect('news');
    }

    public function approveNews(Request $request)
    {
        if (!Auth::user()->is_admin) {
            throw new AuthorizationException();
        }
        $newsId = (int) $request->get('newsId');
        $news = News::findOrFail($newsId);
        $news->approved = 1;
        $news->update();
        return response([(int) $newsId]);
    }
}

app/Http/Controllers/api/v1/NewsController.php
<?php

namespace App\Http\Controllers\api\v1;

use App\Models\AppSettings;
use App\Models\News;
use App\Models\NewsComment;
use App\Models\NewsFavorite;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class NewsController extends BaseAPIController
{

    public function show($newsId)
    {
        $news = News::with('category', 'user', 'topComments')
            ->withCount('comments')
            ->where('id', $newsId)->first();
        $otherNews = News::with('category', 'user', 'topComments')
            ->withCount('comments')
            ->where('id', '<>', $news->id)
            ->orderBy('created_at', 'desc')
            ->take(5)
            ->get();
        return $this->responseJSON([
            'news' => $news,
            'otherNews' => $otherNews->shuffle()
        ]);
    }

    public function search(Request $request)
    {
        $news = News::with('category', 'user', 'topComments')
            ->withCount('comments')
            ->where('title', 'like', '%' . $request->searchText . '%')
            ->where('content', 'like', '%' . $request->searchText . '%')
            ->get();
        return $this->responseJSON($news);
    }

    public function favoritedNews()
    {
        $list = NewsFavorite::with('news')
            ->where('user_id', Auth::user()->id)
            ->get();

        return $this->responseJSON($list->map(function ($item) {
            return $item['news'];
        }));
    }

    public function favoriteNews(Request $request)
    {
        $isFavorited = filter_var($request->isFavorited, FILTER_VALIDATE_BOOLEAN);
        $newsId = $request->newsId;

        if ($isFavorited) {
            if (!NewsFavorite::where('news_id',  $newsId)->where('user_id', Auth::user()->id)->exists()) {
                NewsFavorite::create([
                    'news_id' => $newsId,
                    'user_id' => Auth::user()->id,
                ]);
            }
        } else {
            NewsFavorite::where('news_id',  $newsId)->where('user_id', Auth::user()->id)->delete();
        }

        return $this->responseJSON(
            $request->input()
        );
    }
}

resources/views/news/create.blade.php
@extends('layouts.master')

@section('content')

<h1>Create</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-xl-12">
        <form action="{{route("news.store")}}" method="POST">
            {{ csrf_field() }}
            <input type="hidden" id="image_name" name="image_name" value="{{ old('image_name') }}" />
            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="category_id" class="control-label">Category</label>
                        <select name="category_id" class="form-control">
                            @foreach ($news_categories as $item)
                            <option value="{{ $item->id }}" {{ $item->id == old('category_id') ? "selected" : "" }}>
                                {{ $item->name }}
                            </option>
                            @endforeach
                        </select>
                        <small class="text-validation-error text-danger">{{$errors->first('category_id')}}</small>
                    </div>
                </div>
                <div class="col-sm-3 mt-2">
                    <div class="form-group form-check mt-4">
                        <label class="form-check-label">
                            <input name="featured" type="checkbox" class="form-check-input" {{ filter_var(old('featured'), FILTER_VALIDATE_BOOLEAN) ? "checked" : "" }} /> Featured
                        </label>
                    </div>
                </div>
                <div class="col-sm-3 mt-2">
                    <div class="form-group form-check mt-4">
                        <label class="form-check-label">
                            <input name="visible" type="checkbox" class="form-check-input" {{ filter_var(old('visible', true), FILTER_VALIDATE_BOOLEAN) ? "checked" : "" }} /> Visible
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label for="title" class="control-label">Title</label>
                <input name="title" class="form-control" value="{{ old('title') }}" required />
                <small class="text-validation-error text-danger">{{$errors->first('title')}}</small>
            </div>
            <div class="form-group">
                <label for="content" class="control-label">Content</label>
                <textarea id="content" name="content" class="form-control textarea-editor">{{ old('content') }}</textarea>
                <small class="text-validation-error text-danger">{{$errors->first('content')}}</small>
            </div>
            <div class="form-group">
                <label class="control-label">News Photo</label>
                <input id="imageFile" type="file" required />
                <small class="text-validation-error text-danger">{{$errors->first('image_name')}}</small>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="{{route('news.index')}}">Back to List</a>
</div>

@endsection

@push('scripts')
@include('partials.file_pond_scripts')
<script>
    $(document).ready(() => {
        $('.textarea-editor').summernote({
            height: 300
        });
        createFilePond("imageFile", "image_name");
    });
</script>
@endpush

resources/views/news/edit.blade.php
@extends('layouts.master')

@section('content')

<h1>Edit</h1>

<h4>News</h4>
<hr />
<div class="row">
    <div class="col-xl-12">
        <form action="{{route("news.update", ['id' => $news->id ])}}" method="POST">
            {{ csrf_field() }}
            @method('PUT')
            <input type="hidden" id="image_name" name="image_name" value="{{ old('image_name', $news->image_name) }}" />

            <div class="row">
                <div class="col-sm-6">
                    <div class="form-group">
                        <label for="category_id" class="control-label">Category</label>
                        <select name="category_id" class="form-control">
                            @foreach ($news_categories as $item)
                            <option value="{{ $item->id }}" {{ $item->id == old('category_id', $news->category_id) ? "selected" : "" }}>
                                {{ $item->name }}
                            </option>
                            @endforeach
                        </select>
                        <small class="text-validation-error text-danger">{{$errors->first('category_id')}}</small>
                    </div>
                </div>
                <div class="col-sm-3 mt-2">
                    <div class="form-group form-check mt-4">
                        <label class="form-check-label">
                            <input name="featured" type="checkbox" {{ filter_var(old('featured', $news->featured), FILTER_VALIDATE_BOOLEAN) ? "checked" : "" }} class="form-check-input" /> Featured
                        </label>
                    </div>
                </div>
                <div class="col-sm-3 mt-2">
                    <div class="form-group form-check mt-4">
                        <label class="form-check-label">
                            <input name="visible" type="checkbox" {{ filter_var(old('visible', $news->visible), FILTER_VALIDATE_BOOLEAN) ? "checked" : "" }} class="form-check-input" /> Visible
                        </label>
                    </div>
                </div>
            </div>
            <div class="form-group">
                <label class="control-label">Title</label>
                <input name="title" class="form-control" value="{{ old('title', $news->title) }}" required />
                <small class="text-validation-error text-danger">{{ $errors->first('title') }}</small>
            </div>
            <div class="form-group">
                <label class="control-label">Content</label>
                <textarea name="content" class="form-control textarea-editor">{{ old('content', $news->content) }}</textarea>
                <small class="text-validation-error text-danger">{{ $errors->first('content') }}</small>
            </div>
            <div class="form-group">
                <label class="control-label">News Photo</label>
                <input id="imageFile" type="file" required />
                <small class="text-validation-error text-danger">{{ $errors->first('image_name') }}</small>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a href="{{route('news.index')}}">Back to List</a>
</div>

@endsection

@push('scripts')
@include('partials.file_pond_scripts')
<script>
    $(document).ready(() => {
        $('.textarea-editor').summernote({
            height: 300
        });
        createFilePond("imageFile", "image_name");
    });
</script>
@endpush

resources/views/news/index.blade.php
@extends('layouts.master')

@section('content')

<div class="d-flex flex-row align-items-center">
    <h3>
        News
    </h3>
    <a class="btn btn-info btn-sm ml-auto" href="/news/create">Create News</a>
</div>

<hr />

<table id="newsTable" class="table table-striped">
    <thead>
        <tr>
            <th>
                Featured
            </th>
            <th>
                Title
            </th>
            <th>
                Category
            </th>
            <th>
                Visibility
            </th>
            <th>
                Created Date
            </th>
            <th></th>

        </tr>
    </thead>
    <tbody>
        @foreach ($news as $item)
        <tr>
            <td>
                <input type="checkbox" disabled {{ filter_var($item->featured, FILTER_VALIDATE_BOOLEAN) ? 'checked' : '' }} />
            </td>
            <td>
                {{$item->title}}
            </td>
            <td>
                {{$item->category->name}}
            </td>
            <td>
                {{ filter_var($item->visible, FILTER_VALIDATE_BOOLEAN) ? 'visible' : 'unvisible' }}
            </td>
            <td>
                {{$item->created_at}}
            </td>
            <td>
                @if ($item->approved == 0)
                @if (Auth::user()->is_admin)
                <a href="javascript:void(0);" class="btn btn-success btn-sm" onclick="approveNews(this, {{ $item->id }});"><span data-feather="check"></span> Approve</a>
                @else
                <small><b>not approved yet</b></small>
                @endif
                @endif
                <a href="{{ route('news.edit', ['id' => $item->id]) }}" class="btn btn-info btn-sm"><span data-feather="edit-2"></span></a>
                <a href="javascript:void(0);" data-entity-id="{{$item->id}}" class="btn btn-danger btn-sm delete-btn"><span data-feather="trash-2"></span></a>
            </td>
        </tr>
        @endforeach
    </tbody>
</table>

@include('partials.delete_confirm_modal', ['actionName' => 'news'])

@endsection

@push('scripts')
<script>
    $(document).ready(function () {
        createTable("#newsTable");
    });
    function approveNews(btn, id) {
        $.ajax({
            type: "POST",
            url: "/news/approve_news",
            headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
            dataType: 'json',
            data: {
                newsId: id
            },
            success: () => {
                $(btn).hide();
            }
        })
    }
</script>
@endpush